### ISSUE TITLE
remove the license install in the pkgbuild

### ISSUE THREAD

**Issue by killertofus** [javalsai/lidm#7]
you are using gpl, and gpl is in licenses package required by base https://archlinux.org/packages/core/any/licenses/ https://wiki.archlinux.org/title/PKGBUILD#license

**Comment by javalsai** [comment]
Oh ok, tought I needed to get the license into `/usr/share/licenses/lidm` in some way, but it's just custom ones then. Thanks again! I'll change that ASAP
